---
tags:
  - tutorials
  - jest
  - javascript
---

> Tir√© de la [documentation officielle de Jest](https://archive.jestjs.io/docs/en/asynchronous)

# Tester du code asynchrone

Il est courant d‚Äô√©crire du code asynchrone en JavaScript avec des **promesses** et `async/await`. Jest propose plusieurs fa√ßons de tester ce type de code.

## Tester les promesses

Exemple avec une fonction asynchrone qui retourne une **promesse** :

```javascript
function fetchData() {
  return new Promise((resolve) => {
    setTimeout(() => resolve("Donn√©es r√©cup√©r√©es"), 1000);
  });
}

test("fetchData retourne les bonnes donn√©es", () => {
  return fetchData().then((data) => {
    expect(data).toBe("Donn√©es r√©cup√©r√©es");
  });
});
```

> ‚ö†Ô∏è Il faut **retourner** la promesse dans `test()`, sinon Jest risque de ne pas attendre la fin du test et de le marquer comme r√©ussi trop t√¥t !

### `.resolves` et `.rejects`

Pour tester plus simplement les promesses, Jest propose des **matchers sp√©cifiques** lors qu'une promesse r√©ussit ou √©choue.

```javascript
test("fetchData r√©ussi et retourne les bonnes donn√©es", () => {
  return expect(fetchData()).resolves.toBe("Donn√©es r√©cup√©r√©es");
});
```

```javascript
function fetchDataWithError() {
  return new Promise((_, reject) => {
    setTimeout(() => reject(new Error("Acc√®s limit√©")), 1000);
  });
}

test("fetchData √©choue et renvoie une erreur", () => {
  return expect(fetchDataWithError()).rejects.toThrow("Acc√®s limit√©");
});
```

## `async/await`

Jest supporte nativement `async/await`, de la m√™me mani√®re qu'avec des promesses "classiques".

On peut **attendre** la fin de l‚Äôex√©cution avec `await` :

```javascript
test("fetchData r√©ussi et retourne les bonnes donn√©es", async () => {
  const data = await fetchData();
  expect(data).toBe("Donn√©es r√©cup√©r√©es");
});
```

```javascript
test("fetchData √©choue et renvoie une erreur", async () => {
  await expect(fetchDataWithError()).rejects.toThrow("Acc√®s limit√©");
});
```

Ou avec `try/catch` :

```javascript
test("fetchData √©choue et renvoie une erreur en la catchant", async () => {
  try {
    await fetchDataWithError();
  } catch (error) {
    expect(error).toBeInstanceOf(Error);
    expect(error.message).toBe("Acc√®s limit√©");
  }
});
```

---

## Exercices

Les exercices suivants sont recommand√©s pour ce cours-ci :

- [TBA](#) üöß
